package:
  name: eclipse_pytorch
  version: 0.0.2
source:
  sha256: 7ba3a90441f8537228f24bbd9e546bfd06276fd5255bcaebf4c214d08243d713
  url: https://files.pythonhosted.org/packages/46/ba/18aba0886ccd723fffe2e54011b947b744c31e3fecdbfb196e5acbf56dcb/eclipse_pytorch-0.0.2.tar.gz
about:
  dev_url: https://tcapelle.github.io
  doc_url: https://tcapelle.github.io
  home: https://tcapelle.github.io
  license: Apache Software
  license_family: APACHE
  summary: A pytorch implementation of Eclipse
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - tcapelle
requirements:
  host:
  - pip
  - python
  - packaging
  - torch>1.6
  - fastcore
  run:
  - pip
  - python
  - packaging
  - torch>1.6
  - fastcore
test:
  imports:
  - eclipse_pytorch
