package:
  name: eclipse_pytorch
  version: 0.0.5
source:
  sha256: c8624f0042eb757358224877c36ce3efcce64d32ee0eb8155836444b02874f41
  url: https://files.pythonhosted.org/packages/fa/71/2595dbf8c872b75a9090619fbdb1c52338a7a093b33b7af1443dfd5a0f1f/eclipse_pytorch-0.0.5.tar.gz
about:
  dev_url: https://tcapelle.github.io
  doc_url: https://tcapelle.github.io
  home: https://tcapelle.github.io
  license: Apache Software
  license_family: APACHE
  summary: A pytorch implementation of Eclipse
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - tcapelle
requirements:
  host:
  - pip
  - python
  - packaging
  - torch>1.6
  - fastcore
  run:
  - pip
  - python
  - packaging
  - torch>1.6
  - fastcore
test:
  imports:
  - eclipse_pytorch
