package:
  name: eclipse_pytorch
  version: 0.0.4
source:
  sha256: a89885af33d238dee04973d611eaf243c8aa7963594e6a7b7fd0cdf0ddfc0dce
  url: https://files.pythonhosted.org/packages/e4/b2/3e1d640e98389e122f561afc8d2fd1388c007b7fcafa784715db68b32db3/eclipse_pytorch-0.0.4.tar.gz
about:
  dev_url: https://tcapelle.github.io
  doc_url: https://tcapelle.github.io
  home: https://tcapelle.github.io
  license: Apache Software
  license_family: APACHE
  summary: A pytorch implementation of Eclipse
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - tcapelle
requirements:
  host:
  - pip
  - python
  - packaging
  - torch>1.6
  - fastcore
  run:
  - pip
  - python
  - packaging
  - torch>1.6
  - fastcore
test:
  imports:
  - eclipse_pytorch
