package:
  name: eclipse_pytorch
  version: 0.0.1
source:
  sha256: 2fbc6c0c9dff5c0a90b6eec71fc9ee3921155acf95175fc451a14757ed68dfdd
  url: https://files.pythonhosted.org/packages/b9/62/3cabf593bd6521552802befbf28604bd97122a7d6aacaa51a9417f7d8372/eclipse_pytorch-0.0.1.tar.gz
about:
  dev_url: https://tcapelle.github.io
  doc_url: https://tcapelle.github.io
  home: https://tcapelle.github.io
  license: Apache Software
  license_family: APACHE
  summary: A pytorch implementation of Eclipse
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - tcapelle
requirements:
  host:
  - pip
  - python
  - packaging
  - torch>1.6
  - fastcore
  run:
  - pip
  - python
  - packaging
  - torch>1.6
  - fastcore
test:
  imports:
  - eclipse_pytorch
